plugins {
    id 'java'
    id 'war'
}

group 'vn.edu'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    junitVersion = '5.9.2'
}

sourceCompatibility = '17'
targetCompatibility = '17'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {

    // Jakarta EE 10
    compileOnly 'jakarta.platform:jakarta.jakartaee-api:10.0.0'

    // MariaDB JDBC
    implementation 'org.mariadb.jdbc:mariadb-java-client:3.5.7'

    // JSTL
    implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:3.0.2'
    implementation 'org.glassfish.web:jakarta.servlet.jsp.jstl:3.0.1'

    // CDI cho Tomcat
    implementation 'org.jboss.weld.servlet:weld-servlet-shaded:5.1.4.Final'
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
}

test {
    useJUnitPlatform()
}